simulation:

    time_step: 10
    max_time: 500
    steady_state: False
    force_explicit: False
    force_parallel: False
    max_coupling_iterations: 30


participants:

    Inner-Fluid:
        solver: OpenFOAM
        interfaces:
            - Inner-Fluid-to-Solid

    Outer-Fluid:
        solver: OpenFOAM
        interfaces:
            - Outer-Fluid-to-Solid

    Solid:
        solver: CalculiX
        interfaces:
            - Solid-to-Inner-Fluid
            - Solid-to-Outer-Fluid


couplings:

    -
        - Solid-to-Inner-Fluid
        - Inner-Fluid-to-Solid
    -
        - Solid-to-Outer-Fluid
        - Outer-Fluid-to-Solid
