simulation:

    time-step: 10
    max-time: 500
    steady-state: True
    force-explicit: False
    force-parallel: True
    max-coupling-iterations: 30


participants:

    Inner-Fluid:
        solver: OpenFOAM
        interfaces:
            - {name: Inner-Fluid-to-Solid, patches: [left-patch, right-patch]}
        domain-decomposed: True

    Outer-Fluid:
        solver: OpenFOAM
        interfaces:
            - {name: Outer-Fluid-to-Solid, patches: [interface]}
        domain-decomposed: False

    Solid:
        solver: Code_Aster
        interfaces:
            - {name: Solid-to-Inner-Fluid, patch: inner-interface}
            - {name: Solid-to-Outer-Fluid, patch: outer-interface}
        domain-decomposed: False


couplings:
    - [Solid-to-Inner-Fluid, Inner-Fluid-to-Solid]
    - [Outer-Fluid-to-Solid, Solid-to-Outer-Fluid]